import './onObject/changeColorObject.js'
import './onObject/moveObject.js'
import './onObject/removeObject.js'
import './onObject/renameObject.js'

import './createObject.js'
import './printBlackboard.js'
import './moveForward.js'
import './moveBackward.js'
import './moveLeft.js'
import './moveRight.js'
import './playAnimation.js'
import './pauseGame.js'
import './saveToDatabase.js'
import './copyPaste.js'
import './objectSnapshot.js'
import './printGrid.js'


import './dummyAction.js'